name: 'Build OpenSCAD project'
description: 'Build .scad file on github actions'
author: 'flat35hd99'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  scad_file:
    description: 'Input file'
    required: true
  output_file:
    description: 'Output specified file'
    required: true
    default: 'built.stl'
  options:
    description: "render option"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.scad_file }}
    - ${{ inputs.output_file }}
    - ${{ inputs.options }}
