name: 'Render and build OpenSCAD project'
description: 'OpenSCAD renderer and builder on github actions'
author: 'flat35hd99'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  file:
    description: 'Input file'
    required: true
  output:
    description: 'Output specified file'
    required: true
    default: 'stl'

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'entrypoint.sh'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.output }}
