name: Bulk test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - name: Create galery
        uses: ./
        with:
          scad_file: ./test/
          output_file: ./output/
          target_format_for_bulk: png
          options: "-D size1=10 -D size2=100"
      - name: commit the changes
        run: echo "Please add your upload/commit magic"
      - name: debug ouput
        run: ls ./output/ && cat ./output/README.md
